### ISSUE TITLE
terraform plan error

### ISSUE THREAD

**Issue by ddias00** [rancher/terraform-aws-rke2#131]
![Anotação 2024-02-07 152935](https://github.com/rancher/terraform-aws-rke2/assets/17050697/5c848a48-7682-46af-8d47-25ec376d0c48)

**Comment by matttrach** [comment]
Ahh, sorry. This was introduced in v1.5 of Terraform, what version of Terraform do you use?

**Comment by matttrach** [comment]
https://developer.hashicorp.com/terraform/language/v1.5.x/functions/strcontains

I don't use any version after v1.5 for license reasons, but I test on v1.5.7. You can see in the flake.nix where I have the Terraform version set for my environment. The CI uses the same version.

I can probably make this work for an earlier version if necessary though, please let me know which version is best for you.

**Comment by ddias00** [comment]
![image](https://github.com/rancher/terraform-aws-rke2/assets/17050697/4b4b2b6a-0ca5-4f2e-9fde-cd43694ddcdc)
![image](https://github.com/rancher/terraform-aws-rke2/assets/17050697/957c4577-1bbb-4cd0-9a12-7d067b5d5035)

**Comment by matttrach** [comment]
ok, I will move testing to v1.4.6, update the required version there and make sure you can get everything working. 

So sorry for this! I know that the requirements show v1.2.0, this is just outdated. I should be testing on the minimum required version instead of the maximum. This was totally my fault, I will have an update later today to resolve.

**Comment by ddias00** [comment]
No problem my friend, I'll test version 1.5.0 in parallel

**Comment by ddias00** [comment]
I got it with version 1.5.7, so probably version 1.4.x doesn't work

**Comment by matttrach** [comment]
If you are good with v1.5.7, I will set the minimum version to 1.5 so no one else has issues, that will be a much easier change than downgrading the config and all tests. I don't want to disrupt anyone's workflow, so let me know if this is no good for you.

**Comment by ddias00** [comment]
no problem for me
![image](https://github.com/rancher/terraform-aws-rke2/assets/17050697/4b2cf309-50a7-472b-92f2-0f7e2fdc32aa)

**Comment by matttrach** [comment]
Nice! Thank you! I will have this change out in the next few hours.

**Comment by matttrach** [comment]
This should now be resolved.
Sorry for the wait, but as a bonus, servers will now have EIP provisioned by default so your public IPs won't change when the server is recreated.
