### ISSUE TITLE
Nuke AWS

### ISSUE THREAD

**Issue by matttrach** [rancher/terraform-aws-rke2#23]
Creating a touch point for [hackweek project](https://hackweek.opensuse.org/23/projects/nuke-aws):
Nuke AWS a project by [mtrachier ](https://hackweek.opensuse.org/users/mtrachier)
Updated 14 days ago. 2 hacker ♥️. [3 followers.](https://hackweek.opensuse.org/projects/nuke-aws/followers)

Project Description
Implement /rebuy-de/aws-nuke to make sure no resources are left in AWS after automated tests.

https://github.com/rebuy-de/aws-nuke

Goal for this Hackweek
To implement the nuke and safely destroy resources which are tagged appropriately. This should be an automated step that is run as part of the merge CI for Terraform modules.

A good testing ground would be to generate resources in AWS with the Terraform AWS RKE2 module, then detect and destroy them cleanly with our nuke. We need to be sure that only the resources created by our config are destroyed and that all resources created by our config are destroyed.

https://github.com/rancher/terraform-aws-rke2

Resources
https://github.com/rancher/terraform-aws-rke2
https://github.com/rebuy-de/aws-nuke

**Comment by matttrach** [comment]
I think maybe a good starting point is to investigate how we could implement it here, then move to making an action if that seems easy.

**Comment by matttrach** [comment]
### Primary Use Case
Our current target use case is to remove all generated AWS objects that might be left behind if the testing framework fails or a GitHub action workflow is canceled when running a test in this repo.

A good choice for first test to work with is the "basic" test.

To understand testing, please look at `./tests`:
- this uses Terratest (a Terraform sdk for Go)
- the `./examples` directory holds the tests that Terratest runs
- you can see the 'directory' parameter in the test points to which example it will run
- the utility package in the test module (in file `utility_test.go`) will generate an ssh key
  - this file doesn't run tests, just provides some reusable functions for the other packages
  - this allows the CI to have its own private key without our needing to supply one
  - since the private key is not exposed and is very short living, this is not a security concern
  - we rely on the private key having been already loaded into an ssh agent before the tf is run
  - generating the private key in the testing infra rather than in terraform keeps it from being exposed in the state file

We can simulate failure by manually canceling a test as it runs, but we should be able to clean up manually if that happens.
The easiest way to test would probably be to cancel a manually run test using your own AWS credentials rather than the GH Action CI.
Please make sure that you carefully read the example to see what it generates. I look for 3 things to clean up: an Ec2 instance, an Ec2 key pair, and a security group. This is because the examples are using a few object that already exist in my AWS: a VPC and Subnet tagged with 'Name' = 'default'. This makes sense from the perspective of the test, since we want to test just this module and not the access module. It also makes sense for organizations where the VPC and subnet is managed by a different team than the team managing the cluster.

**Comment by matttrach** [comment]
Another concern with testing to watch out for is that we need to be 100% positive we are only deleting the objects we want, it would be really bad to actually nuke all AWS objects on an account.

**Comment by matttrach** [comment]
This brings up another question: Is AWS Nuke a good strategy?
I included it in this hackweek project because it is mentioned in the AWS documentation and I didn't want to have to build anything from scratch, but maybe we can get by with just using the awscli tool?

**Comment by matttrach** [comment]
https://www.phind.com/search?cache=xl5520mqocr6qb1x4mcwo0hv

**Comment by matttrach** [comment]
https://discord.gg/geMFmmyM

**Comment by ricardobranco777** [comment]
See https://github.com/genevieve/leftovers

**Comment by matttrach** [comment]
That is perfect! Thank you for the suggestion, I will check it out.

**Comment by matttrach** [comment]
# Status

- [ ] add leftovers to flake to try out
- [ ] decide if leftovers is what we want to use
        - already used it to find and clear out some test security groups I wasn't aware of
        - yes we want to use it
- [ ] add nix to CI so that we can use the flake to have arbitrary dependencies
- [ ] add custom "JOB" tag to resources so we can find them later
- [ ] create a workflow that runs on chron and finds previously run jobs, and doesn't find currently running jobs
- [ ] add job to workflow that finds all resources that were created by found jobs and destroys them

**Comment by matttrach** [comment]
Leftovers is finally running on a schedule and detecting problems. This is complete.

**Comment by matttrach** [comment]
https://github.com/rancher/terraform-aws-rke2/actions/runs/7221544198
https://github.com/rancher/terraform-aws-rke2/issues/107
